### ISSUE TITLE
dropdown search gets stuck open

### ISSUE THREAD

**Issue by codydunne** [VisDunneRight/Graph-Layouts#12]
![image](https://github.com/VisDunneRight/gd-comp-eval/assets/2694345/d5a2949f-b987-4371-959e-b57e6651169c)

Console error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')
    at index-d47627e0.js:18:15458
    at Array.forEach (<anonymous>)
    at O_.e.$$.update (index-d47627e0.js:18:15416)
    at Bf (index-d47627e0.js:4:1832)
    at Fu (index-d47627e0.js:4:1547)
```

**Comment by Turokhunter** [comment]
Fixed bug where if you select all items it crashes.
